### ISSUE TITLE
Mouse click selection support?

### ISSUE THREAD

**Issue by kfei** [socketubs/pyhn#27]
It would be great if user can select news with mouse clicking, and then maybe just a double click to open news (as an alternative way to hit Enter).

Not sure how to accomplish this, but there are some console utilities like `htop` have mouse support, and is sometimes a convenient  way.

Thanks!

**Comment by socketubs** [comment]
Mouse support added.
You can select a story by clicking on it and with `ctrl+mouse-left` it will open it in your web browser.

Have a nice day :smile:
